import { SongDocument } from "./song.types";

export const songs: SongDocument[] = [
  {
    id: "song:1",
    name: "Adventure",
    track: "adventure.mp3",
    image: "adventure-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:2",
    name: "All That",
    track: "allthat.mp3",
    image: "allthat-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:3",
    name: "A New Beginning",
    track: "anewbeginning.mp3",
    image: "anewbeginning-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:4",
    name: "Badass",
    track: "badass.mp3",
    image: "badass-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:5",
    name: "Beyond The Line",
    track: "beyondtheline.mp3",
    image: "beyondtheline-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:6",
    name: "Clap And Yell",
    track: "clapandyell.mp3",
    image: "clapandyell-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:7",
    name: "Creative Minds",
    track: "creativeminds.mp3",
    image: "creativeminds-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:8",
    name: "Downtown",
    track: "downtown.mp3",
    image: "downtown-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:9",
    name: "Dreams",
    track: "dreams.mp3",
    image: "dreams-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:10",
    name: "Dubstep",
    track: "dubstep.mp3",
    image: "dubstep-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:11",
    name: "Elevate",
    track: "elevate.mp3",
    image: "elevate-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:12",
    name: "Energy",
    track: "energy.mp3",
    image: "energy-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:13",
    name: "Evolution",
    track: "evolution.mp3",
    image: "evolution-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:14",
    name: "Funday",
    track: "funday.mp3",
    image: "funday-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:15",
    name: "Funky Suspense",
    track: "funkysuspense.mp3",
    image: "funkysuspense-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:16",
    name: "Going Higher",
    track: "goinghigher.mp3",
    image: "goinghigher-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:17",
    name: "Happy Rock",
    track: "happyrock.mp3",
    image: "happyrock-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:18",
    name: "Hey",
    track: "hey.mp3",
    image: "hey-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:19",
    name: "Hip Jazz",
    track: "hipjazz.mp3",
    image: "hipjazz-X2.webp",
    artist: "artist:1",
  },
  {
    id: "song:20",
    name: "Inspire",
    track: "inspire.mp3",
    image: "inspire-X2.webp",
    artist: "artist:2",
  },
  {
    id: "song:21",
    name: "Jazzy Frenchy",
    track: "jazzyfrenchy.mp3",
    image: "jazzyfrenchy-X2.webp",
    artist: "artist:2",
  },
  {
    id: "song:22",
    name: "Little Idea",
    track: "littleidea.mp3",
    image: "littleidea-X2.webp",
    artist: "artist:2",
  },
  {
    id: "song:23",
    name: "Memories",
    track: "memories.mp3",
    image: "memories-X2.webp",
    artist: "artist:2",
  },
  {
    id: "song:24",
    name: "Once Again",
    track: "onceagain.mp3",
    image: "onceagain-X2.webp",
    artist: "artist:2",
  },
  {
    id: "song:25",
    name: "Perception",
    track: "perception.mp3",
    image: "perception-X2.webp",
    artist: "artist:2",
  },
  {
    id: "song:26",
    name: "Photo Album",
    track: "photoalbum.mp3",
    image: "photoalbum-X2.webp",
    artist: "artist:2",
  },
  {
    id: "song:27",
    name: "Piano Moment",
    track: "pianomoment.mp3",
    image: "pianomoment-X2.webp",
    artist: "artist:2",
  },
  {
    id: "song:28",
    name: "Smile",
    track: "smile.mp3",
    image: "smile-X2.webp",
    artist: "artist:3",
  },
  {
    id: "song:29",
    name: "Summer",
    track: "summer.mp3",
    image: "summer-X2.webp",
    artist: "artist:3",
  },
  {
    id: "song:30",
    name: "Sunny",
    track: "sunny.mp3",
    image: "sunny-X2.webp",
    artist: "artist:3",
  },
  {
    id: "song:31",
    name: "Tenderness",
    track: "tenderness.mp3",
    image: "tenderness-X2.webp",
    artist: "artist:3",
  },
  {
    id: "song:32",
    name: "The Lounge",
    track: "ukulele.mp3",
    image: "ukulele-X2.webp",
    artist: "artist:3",
  },
];
