schema: "src/**/*.graphql"
generates:
  __generated__/schema.generated.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      contextType: ../src/server/types#Context
      mappers:
        Song: ../src/domains/song/data-sources/song.types#SongDocument
        Artist: ../src/domains/artist/data-sources/artist.types#ArtistDocument
